In [1]:
import numpy as np
import sys

In [2]:
myarray = np.array([[2, 4, 56, 7]], np.int64) 
# The first parameter is a list of list which is converted to the Numpy array
#  The second parameter is the datatype for each element of the array

In [3]:
myarray

array([[ 2,  4, 56,  7]], dtype=int64)

In [4]:
myarray[0] # prints the 0th row of the array

array([ 2,  4, 56,  7], dtype=int64)

#### In array_name[a, b], a refers to the row no. & b refers to the column no.
#### It returns the bth element of the ath row
###### eg in next 2 cells

In [5]:
myarray[0, 1] # prints the 1st element of the 0th row of the array

4

In [6]:
myarray[0, 0] # prints the 0th element of the 0th row of the array

2

#### array_name.shape returns a tuple in which first element is the no. of rows, second element is the no. of columns
###### eg in next cell

In [7]:
myarray.shape

(1, 4)

In [8]:
myarray[0, 1] = 45 # changes the value of the 1st element of the 0th row of the array to 45

In [9]:
print(myarray[0, 1])

45


# creating numpy arrays using different methods

## METHOD 1 - conversion from python lists, tuples or other data structures

###### The paramter is a list of list which is stored as a numpy array.
####### This method is also used in the beginning of the notebook

In [10]:
array_from_list = np.array([[2, 45, 56, 7], [5, 4, 7, 8], [6, 9, 8, 123]])

In [11]:
array_from_list

array([[  2,  45,  56,   7],
       [  5,   4,   7,   8],
       [  6,   9,   8, 123]])

In [12]:
array_from_list.dtype # prints the datatype of each element of the array

dtype('int32')

In [13]:
array_from_list.shape # prints the no. of rows and no. of columns respectively

(3, 4)

In [14]:
array_from_list.size # prints the total no.of elemants in the array

12

In [15]:
array_from_set = np.array({24, 3, 45})

###### array_from_set.dtype = object 

## NOTE : Avoid using arrays with dtype as objects for efficient calculations, instead use an array with dtype as *int or float*

## METHOD 2 - Using Numpy array creation functions

In [16]:
array_of_zeros = np.zeros((2, 5)) # creatres an array of shape 2,5 with each element as 0.

In [17]:
array_of_zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
array_of_zeros.dtype
array_of_zeros.shape
array_of_zeros.size

10

In [19]:
aranged_array = np.arange(15) # creates an array of integers from 0 to n-1 inclusive of both 0 and n-1, 
# where n is the parameter passed to the function

In [20]:
aranged_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
array_using_linspace = np.linspace(1,5,12)  # returns an array of 12 equally spread numbers between 1 and 5 
                                            # where the first element of the array is 1 and the last element is 5

In [22]:
array_using_linspace

array([1.        , 1.36363636, 1.72727273, 2.09090909, 2.45454545,
       2.81818182, 3.18181818, 3.54545455, 3.90909091, 4.27272727,
       4.63636364, 5.        ])

In [23]:
empty_array = np.empty((4,6)) # creates an array of shape 4,6 with random elements

In [24]:
empty_array

array([[6.95192990e-310, 6.95192989e-310, 0.00000000e+000,
        0.00000000e+000, 1.06637981e-311, 4.94065646e-324],
       [0.00000000e+000, 0.00000000e+000, 4.04738577e-320,
        0.00000000e+000, 1.23022346e-321, 1.06641918e-311],
       [9.88131292e-324, 0.00000000e+000, 0.00000000e+000,
        1.06641917e-311, 3.06320700e-322, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 4.94065646e-324,             nan]])

In [25]:
empty_like_array = np.empty_like(myarray) # creates an array of the shape of the given array with random no.s

In [26]:
empty_like_array

array([[4294967296,          0,       1276,        768]], dtype=int64)

In [27]:
array_using_identity = np.identity(4) # creates an array of shape 4,4

In [28]:
array_using_identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
array_using_identity.shape

(4, 4)

# Numpy Array Functions

In [30]:
array_1 = np.arange(99)

In [31]:
array_1.shape

(99,)

In [32]:
array_2 = array_1.reshape(3,33) # creates an array with the elements of array_1 and shape 3,33
# NOTE : This does not change array_1

In [33]:
array_1.shape
array_2.shape

(3, 33)

In [34]:
array_2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [35]:
array_3 = array_2.ravel() # creates a 1D array with all the elements of array_2
# NOTE : This does not change array

In [36]:
array_3.shape

(99,)

In [37]:
array_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

# axis in numpy

### A 1D array has only one axis i.e. axis0
### A 2D array has only one axis i.e. axis0 and axis1
### and so on...

In a 2D array, the vertical axis, is axis 0 (spans the columns)
               the horizontal axis, is axis 1 (spans the rows)

example: array = [[1, 4, 8],[5, 2, 3],[6, 9, 0],[2, 5, 6]]
##### In the above array,

#    axis1
#    -------------->
#   a| 1 4 8
#   x| 5 2 3
#    i| 6 9 0
#   s| 2 5 6
#   0|
#      \\/
    

In [38]:
array_4 = np.array([[1, 4, 8],[5, 2, 3],[6, 9, 0],[2, 5, 6]])

In [39]:
array_4

array([[1, 4, 8],
       [5, 2, 3],
       [6, 9, 0],
       [2, 5, 6]])

In [40]:
array_4.sum(axis=0) # returns an array of the sum of the elements of each column

array([14, 20, 17])

In [41]:
array_4.sum(axis=1) # returns an array of the sum of the elements of each row

array([13, 10, 15, 13])

In [42]:
array_5 = array_4.T # Transposes the array i.e. the rows becomes the columns and the columns become the rows
# NOTE : This does not change array_4

In [43]:
iterable = array_4.flat # creates an iterable with all the elememts of array_3
# first it uses all the elements of row0, row1, row2 and so on in order
# NOTE : This does not change array_4

In [44]:
for i in iterable:
    print(i)

1
4
8
5
2
3
6
9
0
2
5
6


In [45]:
array_4.ndim # returns the no. of attributes in the array

2

In [46]:
array_4.nbytes # returns the total no. of bytes consumed for storing the array

48

In [47]:
array_6 = np.array([1, 2, 4, 77, 8])

In [48]:
array_6

array([ 1,  2,  4, 77,  8])

In [49]:
array_6.argmax() # returns the index of the largest no. in the array

3

In [50]:
array_6.argmin() # returns the index of the smallest no. in the array

0

In [51]:
array_6.argsort() # creates an array of indices of the values of array_6 in order from smallest to largest
# NOTE : This does not change array_6

array([0, 1, 2, 4, 3], dtype=int64)

In [52]:
array_4.argmin() # return the index of the smallest no. in the array. 
# output is the same as the output obtained from array_4.ravel().argmin()

8

In [53]:
array_4.argmax() # return the index of the largest no. in the array. 
# output is the same as the output obtained from array_4.ravel().argmax()

7

In [54]:
array_4.argmax(axis=0) # returns the index of the largest element in each column

array([2, 2, 0], dtype=int64)

In [55]:
array_4.argmax(axis=1) # returns the index of the largest element in each row

array([2, 0, 1, 2], dtype=int64)

In [56]:
array_4.argmin(axis=0) # returns the index of the smallest element in each column

array([0, 1, 2], dtype=int64)

In [57]:
array_4.argmin(axis=1) # returns the index of the smallest element in each column

array([0, 1, 2, 0], dtype=int64)

In [58]:
array_4.argsort(axis=0) # creates an array of indices of the values of each column of array_4 in order from smallest to largest
# NOTE : This does not change array_4

array([[0, 1, 2],
       [3, 0, 1],
       [1, 3, 3],
       [2, 2, 0]], dtype=int64)

In [59]:
array_4.argsort(axis=1) # creates an array of indices of the values of each row of array_4 in order from smallest to largest
# NOTE : This does not change array_4

array([[0, 1, 2],
       [1, 2, 0],
       [2, 0, 1],
       [0, 1, 2]], dtype=int64)

In [60]:
array_7 = np.array([[1, 0, 4], [3, 6, 7], [4, 3, 2]])

In [61]:
array_8 = np.array([[2, 6, 4], [3, 2, 5], [7, 9, 8]])

In [62]:
array_7 + array_8 # returns an array of the sums of values at corresponding indices

array([[ 3,  6,  8],
       [ 6,  8, 12],
       [11, 12, 10]])

In [63]:
array_7 - array_8 # returns an array of the differences of values at corresponding indices

array([[-1, -6,  0],
       [ 0,  4,  2],
       [-3, -6, -6]])

In [64]:
array_7 * array_8 # returns an array of the products of values at corresponding indices

array([[ 2,  0, 16],
       [ 9, 12, 35],
       [28, 27, 16]])

In [65]:
array_7 / array_8 # returns an array of the results of division of values at corresponding indices

array([[0.5       , 0.        , 1.        ],
       [1.        , 3.        , 1.4       ],
       [0.57142857, 0.33333333, 0.25      ]])

In [66]:
array_7 // array_8 # returns an array of the remainders of division of values at corresponding indices

array([[0, 0, 1],
       [1, 3, 1],
       [0, 0, 0]], dtype=int32)

In [67]:
np.sqrt(array_7) # returns an array of the square root of each value in the array

array([[1.        , 0.        , 2.        ],
       [1.73205081, 2.44948974, 2.64575131],
       [2.        , 1.73205081, 1.41421356]])

In [68]:
array_7.sum() # returns the sum of all the elements of the array

30

In [69]:
array_7.max() # returns the maximum value in the array

7

In [70]:
array_7.min() # returns the minimum value in the array

0

In [71]:
np.where(array_7>4) # returns a tuple of indices of the array where the value is greater than 4

(array([1, 1], dtype=int64), array([1, 2], dtype=int64))

In [72]:
np.count_nonzero(array_7) # returns the total no. of elements which are not 0

8

In [73]:
np.nonzero(array_7) # returns a tuple with one element for each axis where the value is not 0

(array([0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [74]:
array_7.tolist() # creates a python list with the same elements as in the numpy array
# NOTE : This does not change array_7

[[1, 0, 4], [3, 6, 7], [4, 3, 2]]

## Comparing the space occupied by identical python lists and numpy arrays

In [75]:
python_list = [0,4,55,2]

In [76]:
np_array = np.array(python_list)

In [77]:
sys.getsizeof(1) * len(python_list) # returns the space occupied by the python list

112

In [78]:
np_array.itemsize * np_array.size # returns the space occupied by the numpy array

16

In [79]:
###### Therefore, one advantage of numpy arrays is that it uses less storage space.